modLoader="javafml" #mandatory
loaderVersion="47.4.1" #mandatory
license="MPL"
[[mods]]
modId="sob"
version="1.1.4"
displayName="${mod_name}"
authors="ZAPtron_Gamer, squoshi"
description="Food for any and all mods."
[[dependencies.sob]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="create"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="farmersrespite"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.sob]]
    modId="miners_delight"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="mynethersdelight"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="brewinandchewin"
    mandatory=true
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.sob]]
    modId="frycooks_delight"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="blueprint"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.sob]]
    modId="atmospheric"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="autumnity"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="buzzier_bees"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="caverns_and_chasms"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="endergetic"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="neapolitan"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="savage_and_ravage"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="upgrade_aquatic"
    mandatory=false
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sob]]
    modId="jei"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.sob]]
    modId="abnormals_delight"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
